2023-04-19 13:28:41,492 INFO    MainThread:22806 [wandb_setup.py:_flush():71] setting env: {}
2023-04-19 13:28:41,493 INFO    MainThread:22806 [wandb_setup.py:_flush():71] setting login settings: {}
2023-04-19 13:28:41,493 INFO    MainThread:22806 [wandb_init.py:_log_setup():371] Logging user logs to /home/sohui/code/SSL_brats/code/wandb/run-20230419_132841-1ixhq6wq/logs/debug.log
2023-04-19 13:28:41,493 INFO    MainThread:22806 [wandb_init.py:_log_setup():372] Logging internal logs to /home/sohui/code/SSL_brats/code/wandb/run-20230419_132841-1ixhq6wq/logs/debug-internal.log
2023-04-19 13:28:41,493 INFO    MainThread:22806 [wandb_init.py:init():404] calling init triggers
2023-04-19 13:28:41,493 INFO    MainThread:22806 [wandb_init.py:init():409] wandb.init called with sweep_config: {}
config: {}
2023-04-19 13:28:41,493 INFO    MainThread:22806 [wandb_init.py:init():460] starting backend
2023-04-19 13:28:41,494 INFO    MainThread:22806 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-04-19 13:28:41,514 INFO    MainThread:22806 [backend.py:ensure_launched():216] starting backend process...
2023-04-19 13:28:41,523 INFO    MainThread:22806 [backend.py:ensure_launched():221] started backend process with pid: 22902
2023-04-19 13:28:41,525 INFO    MainThread:22806 [wandb_init.py:init():469] backend started and connected
2023-04-19 13:28:41,531 INFO    MainThread:22806 [wandb_init.py:init():533] updated telemetry
2023-04-19 13:28:41,533 INFO    MainThread:22806 [wandb_init.py:init():563] communicating current version
2023-04-19 13:28:42,733 INFO    MainThread:22806 [wandb_init.py:init():568] got version response upgrade_message: "wandb version 0.14.2 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2023-04-19 13:28:42,733 INFO    MainThread:22806 [wandb_init.py:init():578] communicating run to backend with 30 second timeout
2023-04-19 13:29:12,734 INFO    MainThread:22806 [interface_shared.py:_communicate_run():313] couldn't get run from backend
2023-04-19 13:29:12,734 ERROR   MainThread:22806 [wandb_init.py:init():583] backend process timed out
2023-04-19 13:29:12,734 ERROR   MainThread:22806 [wandb_init.py:init():592] encountered error: Error communicating with wandb process
try: wandb.init(settings=wandb.Settings(start_method='fork'))
or:  wandb.init(settings=wandb.Settings(start_method='thread'))
For more info see: https://docs.wandb.ai/library/init#init-start-error
2023-04-19 13:29:31,457 INFO    MainThread:22806 [wandb_init.py:teardown():219] tearing down wandb.init
